# name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - main  

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
     
#       - name: Checkout repository
#         uses: actions/checkout@v3

    
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

 
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: ${{ secrets.DOCKER_USERNAME }}/prod-monitoring:latest  # Replace with 

#       - name: Log out from Docker Hub
#         run: docker logout
name: Build, Run, and Test Node App in Docker

on:
  push:
    branches:
      - main  # Run this action on push to the main branch

jobs:
  test-node-app:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub (optional if you are pulling the image from Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t my-node-app .

      # Run the Docker container
      - name: Run the Docker container
        run: docker run -d -p 8080:8080 --name test-node-app my-node-app

      # Wait for the app to start
      - name: Wait for Node.js app to be ready
        run: sleep 15  # Adjust the sleep time if your app takes longer to start

      # Test if the app is running by making an HTTP request
      - name: Test Node.js app
        run: |
          curl --fail http://localhost:8080 || exit 1

      # Stop and remove the container
      - name: Clean up
        run: docker stop test-node-app && docker rm test-node-app
